name: Pipeline tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # Or 'zulu', 'oracle', etc.
        java-version: '21'

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: target/surefire-reports/
